# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7f48f260cfca0d377070b398384f74c74efd2537d8afaf78e5d7aea310a425da3c27d4e6d024e342285c460117c1f67b411175ba036972072be0c4d19e40ed

test:
  secret_key_base: d4010a1373b11c774220561e6f9027491da84ad77b185dec75e31161577d57ed06844e5c3613b360224dcb3c3757b3509b2a3b8e67e1b581abbd114cb91feff3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
